/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ViewAdmin;

import View.View;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Erwin
 */
public class DaftarKelompok extends javax.swing.JFrame implements View {

    /**
     * Creates new form DaftarKelompok1
     */
    public DaftarKelompok() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ttitleDaftarKelompok = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listLokasi = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        txKelompok = new javax.swing.JTextArea();
        btnBack = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ttitleDaftarKelompok.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ttitleDaftarKelompok.setText("Daftar Kelompok Pada Suatu Lokasi");

        jScrollPane1.setViewportView(listLokasi);

        txKelompok.setColumns(20);
        txKelompok.setRows(5);
        jScrollPane2.setViewportView(txKelompok);

        btnBack.setText("Back");

        btnRefresh.setText("Refresh");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(ttitleDaftarKelompok))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBack)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 295, Short.MAX_VALUE)
                                .addComponent(btnRefresh))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(ttitleDaftarKelompok)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnRefresh))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList listLokasi;
    private javax.swing.JLabel ttitleDaftarKelompok;
    private javax.swing.JTextArea txKelompok;
    // End of variables declaration//GEN-END:variables

    public int getSelectedLokasi() {
        return  listLokasi.getSelectedIndex();
    }

    public void setListLokasi(String list[]) {
        listLokasi.setListData(list);
    }

    public void setKelompok(String s) {
        txKelompok.setText(s);
    }

    public void addAdapter(MouseAdapter me) {
        listLokasi.addMouseListener(me);
    }

    public JButton getBtnRefresh() {
        return btnRefresh;
    }

    public JButton getBtnBack() {
        return btnBack;
    }

    @Override
    public void addListener(ActionListener ae) {
        btnBack.addActionListener(ae);
        btnRefresh.addActionListener(ae);
    }

    @Override
    public void viewErrorMsg(String errorMsg) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
